// Copy the self-hosted UI font (Roboto Flex, variable weight, latin + latin-ext) into skin/fonts
// and emit the matching @font-face rules. Google Sans is proprietary and is only used via local()
// when the viewer has it installed (see src/css/tokens.css).
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';

const SRC = 'node_modules/@fontsource-variable/roboto-flex';
const OUT_FONTS = 'skin/fonts';
const OUT_CSS = 'src/css/generated';
mkdirSync(OUT_FONTS, { recursive: true });
mkdirSync(OUT_CSS, { recursive: true });

const files = ['roboto-flex-latin-wght-normal.woff2', 'roboto-flex-latin-ext-wght-normal.woff2'];
for (const f of files) copyFileSync(`${SRC}/files/${f}`, `${OUT_FONTS}/${f}`);

// fontsource's wght.css carries the correct unicode-range per subset; keep only the two we ship.
const css = readFileSync(`${SRC}/wght.css`, 'utf8');
const blocks = css.split('/*').filter((b) => /latin(-ext)?\s*\*\//.test(b.slice(0, 20)));
const out = blocks
  .map((b) => '/*' + b)
  .join('\n')
  .replace(/url\(\.\/files\//g, 'url(../fonts/')
  .replace(/font-family:\s*'Roboto Flex Variable'/g, "font-family: 'Roboto Flex'");
writeFileSync(
  `${OUT_CSS}/fonts.css`,
  `/* generated by tools/build-fonts.mjs — do not edit */\n${out}\n`
);
console.log(`fonts: ${files.length} files → ${OUT_FONTS}/, ${OUT_CSS}/fonts.css`);
