// Build a tiny Material Symbols Rounded subset (variable FILL axis kept, other axes pinned) from the
// icon names listed in src/icons.txt, and emit one CSS class per icon addressed by PUA codepoint.
// No ligatures involved → no icon-name text flash, no `liga`/`rlig` dependency.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import subsetFont from 'subset-font';

const SRC = 'node_modules/material-symbols/material-symbols-rounded.woff2';
const OUT_FONT = 'skin/fonts/icons.woff2';
const OUT_CSS = 'src/css/generated/icons.css';
mkdirSync('skin/fonts', { recursive: true });
mkdirSync('src/css/generated', { recursive: true });

// name → codepoint (from Google's MaterialSymbols codepoints file)
const cp = new Map(
  readFileSync('tools/material-symbols.codepoints', 'utf8')
    .split('\n')
    .filter(Boolean)
    .map((l) => l.trim().split(/\s+/))
);

// src/icons.txt: one entry per line — `material_name` or `material_name = css-alias`; # comments
const entries = readFileSync('src/icons.txt', 'utf8')
  .split('\n')
  .map((l) => l.replace(/#.*/, '').trim())
  .filter(Boolean)
  .map((l) => {
    const [name, alias] = l.split('=').map((s) => s.trim());
    return { name, alias: alias || name.replace(/_/g, '-') };
  });

const missing = entries.filter((e) => !cp.has(e.name)).map((e) => e.name);
if (missing.length) {
  console.error('icons: unknown Material Symbols names:', missing.join(', '));
  process.exit(1);
}

const text = [
  ...new Set(entries.map((e) => String.fromCodePoint(parseInt(cp.get(e.name), 16)))),
].join('');
const buf = await subsetFont(readFileSync(SRC), text, {
  targetFormat: 'woff2',
  noLayoutClosure: true,
  variationAxes: { FILL: { min: 0, max: 1 }, wght: 400, GRAD: 0, opsz: 24 },
});
writeFileSync(OUT_FONT, buf);

const css = [
  '/* generated by tools/build-icons.mjs — do not edit */',
  '@font-face {',
  "  font-family: 'gm-icons';",
  '  font-style: normal;',
  '  font-weight: 400;',
  '  font-display: block;',
  "  src: url(../fonts/icons.woff2) format('woff2');",
  '}',
  ...entries.map((e) => `.ico-${e.alias}::before { content: '\\${cp.get(e.name)}'; }`),
  '',
  '/* codepoint variables for component CSS: content: var(--ico-<alias>) */',
  ':root {',
  ...entries.map((e) => `  --ico-${e.alias}: '\\${cp.get(e.name)}';`),
  '}',
  '',
].join('\n');
writeFileSync(OUT_CSS, css);
console.log(
  `icons: ${entries.length} icons → ${OUT_FONT} (${(buf.length / 1024).toFixed(1)} KB), ${OUT_CSS}`
);
